version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/Integratietests"
    schedule:
      interval: "daily"

  - package-ecosystem: "nuget"
    directory: "/MobyPark"
    schedule:
      interval: "daily"

  - package-ecosystem: "nuget"
    directory: "/MobyParkxUnitTest"
    schedule:
      interval: "daily"