// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MobyPark.Data;

#nullable disable

namespace MobyPark.Migrations
{
    [DbContext(typeof(UserDbContext))]
    partial class UserDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // -------------------------------
            // ParkingSession
            // -------------------------------
            modelBuilder.Entity("MobyPark.Entities.ParkingSession", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTimeOffset?>("CancelledAt")
                    .HasColumnType("datetimeoffset");

                b.Property<decimal>("Cost")
                    .HasPrecision(10, 2)
                    .HasColumnType("decimal(10,2)");

                b.Property<int>("DurationMinutes")
                    .HasColumnType("int");

                b.Property<bool>("IsCancelled")
                    .HasColumnType("bit");

                b.Property<bool>("IsRefunded")
                    .HasColumnType("bit");

                b.Property<string>("LicensePlate")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<string>("PaymentStatus")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<DateTimeOffset?>("RefundDate")
                    .HasColumnType("datetimeoffset");

                b.Property<DateTimeOffset>("Started")
                    .HasColumnType("datetimeoffset");

                b.Property<DateTimeOffset?>("Stopped")
                    .HasColumnType("datetimeoffset");

                b.Property<Guid>("UserId")
                    .HasColumnType("uniqueidentifier");

                b.Property<int>("VehicleId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("VehicleId");

                b.HasIndex("UserId", "Started");

                b.ToTable("ParkingSessions");
            });

            // -------------------------------
            // Payment
            // -------------------------------
            modelBuilder.Entity("MobyPark.Entities.Payment", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<decimal>("Amount")
                    .HasColumnType("decimal(18,2)");

                b.Property<bool>("Completed")
                    .HasColumnType("bit");

                b.Property<string>("Hash")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<Guid>("Initiator")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Transaction")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.HasIndex("Initiator");

                b.ToTable("Payments");
            });

            // -------------------------------
            // Reservation
            // -------------------------------
            modelBuilder.Entity("MobyPark.Entities.Reservation", b =>
            {
                b.Property<int>("ReservationId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationId"));

                b.Property<DateTimeOffset>("EndTime")
                    .HasColumnType("datetimeoffset");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit");

                b.Property<string>("LicensePlate")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("ParkingLotId")
                    .HasColumnType("int");

                b.Property<DateTimeOffset>("StartTime")
                    .HasColumnType("datetimeoffset");

                b.Property<Guid>("UserId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("ReservationId");

                b.ToTable("Reservations");
            });

            // -------------------------------
            // User
            // -------------------------------
            modelBuilder.Entity("MobyPark.Entities.User", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<int>("BirthYear")
                    .HasColumnType("int");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(70)
                    .HasColumnType("nvarchar(70)");

                b.Property<string>("PasswordHash")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("PhoneNumber")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("nvarchar(30)");

                b.Property<string>("RefreshToken")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTimeOffset?>("RefreshTokenExpiryTime")
                    .HasColumnType("datetimeoffset");

                b.Property<int>("Role")
                    .HasColumnType("int");

                b.Property<string>("Username")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.HasKey("Id");

                b.ToTable("Users");
            });

            // -------------------------------
            // Vehicle
            // -------------------------------
            modelBuilder.Entity("MobyPark.Entities.Vehicle", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Color")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("nvarchar(30)");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("LicensePlate")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<string>("Make")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("Model")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<Guid>("UserId")
                    .HasColumnType("uniqueidentifier");

                b.Property<int>("Year")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("UserId", "LicensePlate")
                    .IsUnique();

                b.ToTable("Vehicles");
            });

            // -------------------------------
            // Relationships
            // -------------------------------
            modelBuilder.Entity("MobyPark.Entities.ParkingSession", b =>
            {
                b.HasOne("MobyPark.Entities.User", "User")
                    .WithMany("ParkingSessions")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("MobyPark.Entities.Vehicle", "Vehicle")
                    .WithMany()
                    .HasForeignKey("VehicleId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("User");
                b.Navigation("Vehicle");
            });

            modelBuilder.Entity("MobyPark.Entities.Payment", b =>
            {
                b.HasOne("MobyPark.Entities.User", "User")
                    .WithMany("Payments")
                    .HasForeignKey("Initiator")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("User");
            });

            modelBuilder.Entity("MobyPark.Entities.Vehicle", b =>
            {
                b.HasOne("MobyPark.Entities.User", "User")
                    .WithMany("Vehicles")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("User");
            });

            modelBuilder.Entity("MobyPark.Entities.User", b =>
            {
                b.Navigation("ParkingSessions");
                b.Navigation("Payments");
                b.Navigation("Vehicles");
            });
#pragma warning restore 612, 618
        }
    }
}
